
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzfcczdsyrmqoryyawyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6ZmNjemRzeXJtcW9yeXlhd3lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDU5MDUsImV4cCI6MjA1Nzc4MTkwNX0.JcWgAi7TAPlGF_4wS43DJ7ElKmtdY8rcYtxqBBrOLws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to check if a user is authenticated
export const isAuthenticated = async () => {
  const { data: { session } } = await supabase.auth.getSession();
  return !!session;
};

// Helper function to get the current user's ID
export const getCurrentUserId = async () => {
  const { data: { session } } = await supabase.auth.getSession();
  return session?.user?.id;
};

// Helper function to get user profile data
export const getUserProfile = async () => {
  const { data: { session } } = await supabase.auth.getSession();
  if (!session) return null;
  
  const { data, error } = await supabase
    .from('profiles')
    .select('*')
    .eq('id', session.user.id)
    .single();
    
  if (error || !data) return null;
  return data;
};

// Helper function to update user profile
export const updateUserProfile = async (profile: { name?: string; phone?: string; }) => {
  const { data: { session } } = await supabase.auth.getSession();
  if (!session) return { error: 'Not authenticated' };
  
  const { data, error } = await supabase
    .from('profiles')
    .update(profile)
    .eq('id', session.user.id);
    
  return { data, error };
};
